### ISSUE TITLE
No aggregate risk heterogeneous agents.

### ISSUE THREAD

**Issue by albop** [EconForge/dolo#79]
The goal is to have a proof of concept implementation of an heterogeneous agents model. It would be defined by:
- a dtcscc model
- distributions for the parameters of the individual decisions
- aggregate clearing conditions  which would depend on all states/controls/parameters. These aggregate conditions would be associated to a list of free parameters, which would be common to all agents

Here is a tentative yaml file describing the problem to solve: https://github.com/EconForge/heterogeneous_agents_workshop/blob/master/examples/consumption_savings_bewley.yaml . Look at this file as a kind of "challenge". I propose to address this challenge in two different phases:
## Proof-of-concept phase (with a small number of agents)
1. parse the yaml file (which consist in two documents) to produce:
   - a dtcscc model
   - a data-structure describing the heterogeneity (distribution of coeffs, etc.). Use a quick hack to deal with the symbolic expressions. (example below)# 
2. write a routine, which solves the individual model many times, taking parameters from the distribution. This can reuse the solution routines already in dolo
3. simulate all solutions
4. compute the residual of all aggregate clearing conditions
5. redo 2-3-4 for various values of the free parameter to be adjusted until the residuals are 0. This outer loop can be done many ways. I suggest grid search for the first try so that we can plot the residuals.
## More efficient phase (output can be compared with the former phase, which is still usefull for debugging anyway).
1. solve the model for many parameters at once in a vectorized way
2. simulate the solutions of many model values at once
## In the process, some simple tasks which will increase happiness:
- write routines to study the resulting distributions
- write a `__repr__/__html__` routine to represent the heterogeneous model in a beautiful way
- propose ways to write the aggregate conditions in the yaml file (which will be considered when redesigning the language).
- think about algorithmic improvements
## Quick hacks:
- for `s = 'i -> i/n*0.1'` one could do: `fun = eval( 'lambda {}: {}'.format( *str.split(s,'->')) )`
- for: `sum([i,j], m[i,j]-c[i,j])` one can redo the lambda trick or rewrite `s = "sum(m-c)"` and use numexpr.evaluate(s) which produces the desired answer when m and c are 2d matrices

**Comment by albop** [comment]
The goal is to have a proof of concept implementation of an heterogeneous agents model. It would be defined by:
- a dtcscc model
- distributions for the parameters of the individual decisions
- aggregate clearing conditions  which would depend on all states/controls/parameters. These aggregate conditions would be associated to a list of free parameters, which would be common to all agents

Here is a tentative yaml file describing the problem to solve: https://github.com/EconForge/heterogeneous_agents_workshop/blob/master/examples/consumption_savings_bewley.yaml . Look at this file as a kind of "challenge". I propose to address this challenge in two different phases:

## Proof-of-concept phase (with a small number of agents)

1. parse the yaml file (which consist in two documents) to produce:
    - a dtcscc model
    - a data-structure describing the heterogeneity (distribution of coeffs, etc.). Use a quick hack to deal with the symbolic expressions. (example below)# 
2. write a routine, which solves the individual model many times, taking parameters from the distribution. This can reuse the solution routines already in dolo
3. simulate all solutions
4. compute the residual of all aggregate clearing conditions
5. redo 2-3-4 for various values of the free parameter to be adjusted until the residuals are 0. This outer loop can be done many ways. I suggest grid search for the first try so that we can plot the residuals.

## More efficient phase (output can be compared with the former phase, which is still usefull for debugging anyway).

2. solve the model for many parameters at once in a vectorized way
3. simulate the solutions of many model values at once

## In the process, some simple tasks which will increase happiness:

- write routines to study the resulting distributions
- write a `__repr__/__html__` routine to represent the heterogeneous model in a beautiful way
- propose ways to write the aggregate conditions in the yaml file (which will be considered when redesigning the language).
- think about algorithmic improvements

## Quick hacks:

- for `s = 'i -> i/n*0.1'` one could do: `fun = eval( 'lambda {}: {}'.format( *str.split(s,'->')) )`
- for: `sum([i,j], m[i,j]-c[i,j])` one can redo the lambda trick or rewrite `s = "sum(m-c)"` and use numexpr.evaluate(s) which produces the desired answer when m and c are 2d matrices

**Comment by albop** [comment]
I have updated a bit the roadmap, so as to provide more intermediate goals.

**Comment by spencerlyon2** [comment]
This is great, thanks for filling that out. 

@wupeifan are you open to helping us work on this?

**Comment by spencerlyon2** [comment]
I started looking at this. I realized that the yaml file in the link it a dtmscc model (discrete time, mixed state, continuous control) model, not a dtcscc (discrete time, continuous state, continuous control) model.

I tried to adapt it to be dtcscc and this is what I have:

```yaml
name: bewley_dtcscc

symbols:
    states: [z, m]  # cash in hand (note that savings (a) is a = m - exp(z))
    controls: [c]  # consumption
    auxiliaries: [a]
    parameters: [beta, gamma, r, T, b, rho, zbar, sig_z]  # borrowing constraint a' >= -b
    shocks: [e_z]

equations:

    transition:
        - z = (1-rho)*zbar + rho*z(-1) + e_z
        - m = (m(-1)-c(-1))*r + exp(z)
    auxiliary:
        - a = m - exp(z)
    arbitrage:
        # Euler equation                |  borrowing constraint
        - 1 = beta*r*(c(1)/c)^(-gamma)  |  0 <= c <= m + b

calibration:
    # parameter values
    beta:  0.95
    gamma: 4.00
    r:     1.02  # should be 1/beta by SS euler equation
    T:     100
    b:     0.0
    rho:   0.9
    zbar:  0
    sig_z: 0.016
    # steady-state values
    c:     1.0  # normalization because SS euler equation is 1 = beta*r
    z:     zbar
    m:     (exp(z) - r*c) / (1-r)
    a:     m - exp(z)

covariances:
      [[ sig_z**2]]

options:

    approximation_space:
        a: [ zbar-2*sig_z, m*0.8 ]
        b: [ zbar+2*sig_z, m*1.2 ]
        orders: [10, 50]
        horizon: T
```

I have a couple issues here:

- The steady state version of the euler equation (arbitrage equation) is `1 = beta*r`. We can set this in calibration, but it doesn't help us pin down a steady state in terms of consumption, so I normalized consumption to be 1.0.
- When try to pass this model through the `time_iteration` algorithm, I get a `BlanchardKahnError` because the system has 2 explosive eigenvalues. I think this is related to the problem above.

Any suggestions on how to alter what I have to have a baseline dtcscc Bewley model to work with?
