### ISSUE TITLE
Add a `functions` block in the `definitions` section

### ISSUE THREAD

**Issue by spencerlyon2** [EconForge/dolo#84]
I was thinking it might be nice to have a `functions` block in the `definitions` section. It's easiest to see why I want this by looking at this example (FYI, I've deleted most of the file):

```yaml
# Model in chapter 11 of Recursive Macroeconomic Theory 3rd edition by
# Ljvinquist and Sargent
name: fiscal_growth_international
model_type: dtcscc

symbols:
    states: [B, k, kf, tau_c, tau_k, tau_cf, tau_kf]
    controls: [c, cf, i_B]
    auxiliaries: [y, yf, eta, w, etaf, wf, R]
    shocks: [g, exog_tau_c, exog_tau_k, gf, exog_tau_cf, exog_tau_kf]
    parameters: [beta, gamma, delta, alpha, A, mu_star]

equations:

    arbitrage:
        ###
    transition:
        ###
    auxiliary:
        # production function
        - y = A*k^alpha
        - yf = A*kf^alpha
```

Notice that we assume the production function is the same. It would be nice to do something like this:

```yaml
definitions:
    functions:
        f:
            args: x
            body: A*x^alpha
```

Here we would create a one argument function `f` that specifies the production function. We would implicitly pass the parameters also

We could then use it like this:

```yaml
equations:
    auxiliary:
        - y = f(k)
        - yf = f(kf)
```

In this particular example the production function is so small that it isn't really worth the effort, but we can imagine cases where this would extremely useful.
