### ISSUE TITLE
ENH: merging options

### ISSUE THREAD

**Issue by albop** [EconForge/dolo#94]
It would be nice to to have a unified way to reuse data specified in `options:` section as a function argument. A simple example is the `grid` argument:
- in the model file:
```
options:
    grid: !Cartesian
        a: [0,0]
        b: [1,1]
        orders: [20,20]
```
- the time-iteration has a grid argument, which can be used to replace or augment the one given in options:

```dr = time_iteration(model, grid={'a':[0,0]})```

Loosely speaking, the behaviour of the `grid` option, should be understood as a kind of tree merge with the following rules:
- language object `Object(a=3)` is equivalent to `{'type':'Object', 'a':3}`
- `merge( {'a': {'b': 1,'c':2}}, {'a':{'b':3,'d':4}} ) -> {'a':{'b':3,'c':2, 'd':4}}`
